parent_dir = "exp/insurance/TVAE"
real_data_path = "Dataset/insurance/real"
dataname = "insurance"
seed = 0
device = "cuda"
task_type = "regression"
num_classes = 0
num_numerical_features = 2
num_categorical_features = 4
num_categorical = [
    2,
    6,
    2,
    4,
]
X_num_columns = [
    "age",
    "bmi",
]
X_cat_columns = [
    "sex",
    "children",
    "smoker",
    "region",
]
y_column = [
    "charges",
]

[train_params]
epochs = 30000
embedding_dim = 512
batch_size = 4096
loss_factor = 1.1675626917524105
compress_dims = [
    256,
    512,
]
decompress_dims = [
    256,
    512,
]

[sample]
seed = 0
num_samples = 869

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "None"
y_plus1 = false
