parent_dir = "exp/abalone/CTGAN"
real_data_path = "Dataset/abalone/real"
dataname = "abalone"
seed = 0
device = "cuda"
task_type = "regression"
num_classes = 0
num_numerical_features = 7
num_categorical_features = 1
num_categorical = [
    3,
]
X_num_columns = [
    "Length",
    "Diameter",
    "Height",
    "Whole weight",
    "Shucked weight",
    "Viscera weight",
    "Shell weight",
]
X_cat_columns = [
    "Sex",
]
y_column = [
    "Rings",
]

[train_params]
epochs = 20000
batch_size = 1000

[sample]
seed = 0
num_samples = 2923

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "None"
y_plus1 = false
