parent_dir = "exp/buddy/TabSyn"
real_data_path = "Dataset/buddy/"
task_type = "multiclass"
num_classes = 3
num_numerical_features = 2
num_categorical_features = 5
num_categorical = [
    4,
    56,
    20,
    10,
    4,
]
seed = 0
device = "cuda"
X_num_columns = [
    "length(m)",
    "height(cm)",
]
X_cat_columns = [
    "condition",
    "color_type",
    "X1",
    "X2",
    "breed_category",
]
y_column = [
    "pet_category",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "None"
y_plus1 = false

[VAE]
lr = 0.001
wd = 0
d_token = 4
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024

[model_params]
is_y_cond = false
batch_size = 4096
num_epochs = 10001

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "None"
