parent_dir = "exp/churn/TabSyn"
real_data_path = "Dataset/churn/"
task_type = "binclass"
num_classes = 2
num_numerical_features = 5
num_categorical_features = 5
num_categorical = [
    3,
    2,
    4,
    2,
    2,
]
seed = 0
device = "cuda"
X_num_columns = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "EstimatedSalary",
]
X_cat_columns = [
    "Geography",
    "Gender",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
]
y_column = [
    "Exited",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.001
wd = 0
d_token = 4
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024

[model_params]
is_y_cond = false
batch_size = 4096
num_epochs = 10001

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
