parent_dir = "exp/abalone/CoTable"
real_data_path = "Dataset/abalone/"
task_type = "regression"
dataname = "abalone"
num_classes = 3
num_numerical_features = 8
num_categorical_features = 0
num_categorical = []
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "Length",
    "Diameter",
    "Height",
    "Whole weight",
    "Shucked weight",
    "Viscera weight",
    "Shell weight",
    "Rings",
]
X_cat_columns = []
y_column = [
    "Sex",
]
X_num_columns_real = [
    "Length",
    "Diameter",
    "Height",
    "Whole weight",
    "Shucked weight",
    "Viscera weight",
    "Shell weight",
]
X_cat_columns_real = [
    "Sex",
]
y_column_real = [
    "Rings",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "None"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.008
epoch = 15000
wd = 0
d_token = 5
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024
scheduler_fac = 0.98
scheduler_patience = 10

[model_params]
is_y_cond = true
d_in = 40
dim_t = 128
feedforward_layer = [
    512,
    1024,
    1024,
    512,
]
depth = 1
ff_dropout = 0.0
activation = "reglu"
bert = "prajjwal1/bert-tiny"
bert_max_length = 10

[model_params.attention]
n_head = 2
attention_dropout = 0.0

[ddpm]
num_Timesteps = 1000
drop_prob_of_context_mask = 0.9
gaussian_loss_type = "mse"
schedule_name = "linear_beta_schedule"
use_guide = false
guide_w = 2

[ddpm_train]
epoch = 50000
lr = 0.001
lr_min = 5e-08
weight_decay = 0.0
batch_size = 1024

[ddpm_train.lr_scheduler]
step_size = 15
gamma = 0.988

[sample]
device = "cuda"
batch_size = 10000
n_sample_of_each_class = 10000
seed = 0

[eval.Transform]
seed = 0
normalization = "None"
cat_encode_policy = "None"
y_policy = "None"
y_plus1 = false
