parent_dir = "exp/buddy/CoTable"
real_data_path = "D:/Study/自学/表格数据生成/v11/Dataset/buddy/"
task_type = "multiclass"
num_classes = 3
num_numerical_features = 2
num_categorical_features = 5
num_categorical = [
    4,
    56,
    20,
    10,
    4,
]
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "length(m)",
    "height(cm)",
]
X_cat_columns = [
    "condition",
    "color_type",
    "X1",
    "X2",
    "breed_category",
]
y_column = [
    "pet_category",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "None"
y_plus1 = false

[VAE]
lr = 0.005
epoch = 15000
wd = 0
d_token = 5
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024
scheduler_fac = 0.982
scheduler_patience = 5

[model_params]
is_y_cond = true
d_in = 35
dim_t = 128
feedforward_layer = [
    512,
    1024,
    512,
]
depth = 2
ff_dropout = 0.0
activation = "reglu"
bert = "prajjwal1/bert-tiny"
bert_max_length = 9

[model_params.attention]
n_head = 2
attention_dropout = 0.0

[ddpm]
num_Timesteps = 1000
drop_prob_of_context_mask = 0.9
gaussian_loss_type = "mse"
schedule_name = "linear_beta_schedule"
use_guide = false
guide_w = 2

[ddpm_train]
epoch = 30000
lr = 0.003
lr_min = 5e-08
weight_decay = 0.0
batch_size = 2048

[ddpm_train.lr_scheduler]
step_size = 15
gamma = 0.987

[sample]
device = "cuda"
batch_size = 20000
n_sample_of_each_class = 10000
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "None"
y_plus1 = false
