parent_dir = "exp/magic/CTGAN"
real_data_path = "Dataset/magic/"
dataname = "magic"
seed = 0
device = "cuda"
task_type = "binclass"
num_classes = 2
num_numerical_features = 10
num_categorical_features = 0
num_categorical = []
X_num_columns = [
    "Length",
    "Width",
    "Size",
    "Conc",
    "Conc1",
    "Asym",
    "M3Long",
    "M3Trans",
    "Alpha",
    "Dist",
]
X_cat_columns = []
y_column = [
    "class",
]

[train_params]
epochs = 20000
batch_size = 1000

[sample]
seed = 0
num_samples = 13313

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
