parent_dir = "exp/bean/CoDi"
real_data_path = "Dataset/bean/"
task_type = "multiclass"
dataname = "bean"
num_classes = 7
num_numerical_features = 16
num_categorical_features = 0
num_categorical = []
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "Area",
    "Perimeter",
    "MajorAxisLength",
    "MinorAxisLength",
    "AspectRation",
    "Eccentricity",
    "ConvexArea",
    "EquivDiameter",
    "Extent",
    "Solidity",
    "roundness",
    "Compactness",
    "ShapeFactor1",
    "ShapeFactor2",
    "ShapeFactor3",
    "ShapeFactor4",
]
X_cat_columns = []
y_column = [
    "Class",
]

[Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "one-hot"
y_policy = "one-hot"
y_plus1 = false

[model_params]
is_y_cond = false
dataname = "magic"
encoder_dim_con = [
    64,
    128,
    256,
]
encoder_dim_dis = [
    64,
    128,
    256,
]
nf_con = 16
nf_dis = 64
mean_type = "epsilon"
var_type = "fixedsmall"
activation = "relu"
training_batch_size = 2100
eval_batch_size = 2100
total_epochs_both = 10000
T = 50
beta_1 = 1e-05
beta_T = 0.02
lr_con = 0.002
lr_dis = 0.002
grad_clip = 1
parallel = false
sample_step = 2000
ns_method = 0
lambda_con = 0.2
lambda_dis = 0.2

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
