parent_dir = "exp/obesity/GReaT"
real_data_path = "Dataset/obesity/"
task_type = "multiclass"
dataname = "obesity"
num_classes = 7
num_numerical_features = 8
num_categorical_features = 8
num_categorical = [
    2,
    2,
    2,
    4,
    2,
    2,
    4,
    5,
]
device = "cuda"
X_num_columns = [
    "Age",
    "Height",
    "Weight",
    "FCVC",
    "NCP",
    "CH2O",
    "FAF",
    "TUE",
]
X_cat_columns = [
    "Gender",
    "family_history_with_overweight",
    "FAVC",
    "CAEC",
    "SMOKE",
    "SCC",
    "CALC",
    "MTRANS",
]
y_column = [
    "NObeyesdad",
]

[model_params]
dataname = "obesity"
batch_size = 16

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
