parent_dir = "exp/shopper/TabSyn"
real_data_path = "Dataset/shopper/"
dataname = "shopper"
task_type = "binclass"
num_classes = 2
num_numerical_features = 10
num_categorical_features = 7
num_categorical = [
    10,
    8,
    13,
    9,
    20,
    3,
    2,
]
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
]
X_cat_columns = [
    "Month",
    "OperatingSystems",
    "Browser",
    "Region",
    "TrafficType",
    "VisitorType",
    "Weekend",
]
y_column = [
    "Revenue",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.001
wd = 0
d_token = 4
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024

[model_params]
is_y_cond = false
batch_size = 4096
num_epochs = 10001

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
