parent_dir = "exp/adult/CoTable"
real_data_path = "Dataset/adult/"
dataname = "adult"
task_type = "binclass"
num_classes = 2
num_numerical_features = 6
num_categorical_features = 8
num_categorical = [
    9,
    16,
    7,
    15,
    6,
    5,
    2,
    42,
]
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "age",
    "fnlwgt",
    "education_num",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
]
X_cat_columns = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]
y_column = [
    "salary",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.008
epoch = 10000
wd = 0
d_token = 5
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024
scheduler_fac = 0.98
scheduler_patience = 10

[model_params]
is_y_cond = true
d_in = 70
dim_t = 128
feedforward_layer = [
    1024,
    2048,
    1024,
]
depth = 2
ff_dropout = 0.0
activation = "reglu"
bert = "prajjwal1/bert-tiny"

[model_params.attention]
n_head = 1
attention_dropout = 0.0

[ddpm]
num_Timesteps = 1000
drop_prob_of_context_mask = 0.9
gaussian_loss_type = "mse"
schedule_name = "linear_beta_schedule"
use_guide = false
guide_w = 2

[ddpm_train]
epoch = 200000
lr = 0.002
lr_min = 5e-06
weight_decay = 0.0
batch_size = 1024

[ddpm_train.lr_scheduler]
step_size = 15
gamma = 0.985

[sample]
device = "cuda"
batch_size = 26048
n_sample_of_each_class = 10000
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
