parent_dir = "exp/productivity/STaSy"
real_data_path = "Dataset/productivity/real"
task_type = "regression"
dataname = "productivity"
num_classes = 0
num_numerical_features = 10
num_categorical_features = 3
num_categorical = [
    5,
    2,
    6,
]
device = "cuda"
X_num_columns = [
    "team",
    "targeted_productivity",
    "smv",
    "wip",
    "over_time",
    "incentive",
    "idle_time",
    "idle_men",
    "no_of_style_change",
    "no_of_workers",
]
X_cat_columns = [
    "quarter",
    "department",
    "day",
]
y_column = [
    "actual_productivity",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "one-hot"
y_policy = "quantile"
y_plus1 = false

[model_params]
is_y_cond = false
dataname = "productivity"

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "None"
cat_encode_policy = "None"
y_policy = "None"
