parent_dir = "exp/obesity/CoTable"
real_data_path = "Dataset/obesity/"
dataname = "obesity"
task_type = "multiclass"
num_classes = 7
num_numerical_features = 8
num_categorical_features = 8
num_categorical = [
    2,
    2,
    2,
    4,
    2,
    2,
    4,
    5,
]
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "Age",
    "Height",
    "Weight",
    "FCVC",
    "NCP",
    "CH2O",
    "FAF",
    "TUE",
]
X_cat_columns = [
    "Gender",
    "family_history_with_overweight",
    "FAVC",
    "CAEC",
    "SMOKE",
    "SCC",
    "CALC",
    "MTRANS",
]
y_column = [
    "NObeyesdad",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.005
epoch = 100000
wd = 0
d_token = 5
token_bias = true
n_head = 1
factor = 128
num_layers = 2
batch_size = 512
scheduler_fac = 0.985
scheduler_patience = 10

[model_params]
is_y_cond = true
d_in = 80
dim_t = 128
feedforward_layer = [
    1024,
    2048,
    1024,
]
depth = 2
ff_dropout = 0.0
activation = "reglu"
bert = "prajjwal1/bert-tiny"
bert_max_length = 12

[model_params.attention]
n_head = 1
attention_dropout = 0.0

[ddpm]
num_Timesteps = 1000
drop_prob_of_context_mask = 0.9
gaussian_loss_type = "mse"
schedule_name = "linear_beta_schedule"
use_guide = false
guide_w = 2

[ddpm_train]
epoch = 300000
lr = 0.003
lr_min = 5e-08
weight_decay = 0.0
batch_size = 512

[ddpm_train.lr_scheduler]
step_size = 15
gamma = 0.987

[sample]
device = "cuda"
batch_size = 20000
n_sample_of_each_class = 10000
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
