parent_dir = "exp/obesity/smote"
real_data_path = "Dataset/obesity/"
task_type = "binclass"
dataname = "obesity"
num_classes = 7
num_numerical_features = 8
num_categorical_features = 8
num_categorical = [
    2,
    2,
    2,
    4,
    2,
    2,
    4,
    5,
]
device = "cuda"
X_num_columns = [
    "Age",
    "Height",
    "Weight",
    "FCVC",
    "NCP",
    "CH2O",
    "FAF",
    "TUE",
]
X_cat_columns = [
    "Gender",
    "family_history_with_overweight",
    "FAVC",
    "CAEC",
    "SMOKE",
    "SCC",
    "CALC",
    "MTRANS",
]
y_column = [
    "NObeyesdad",
]

[smote_params]
k_neighbours = 5
frac_samples = 1
frac_lam_del = 0.65

[sample]
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
