parent_dir = "exp/bean/CTGAN"
real_data_path = "Dataset/bean/"
dataname = "bean"
seed = 0
device = "cuda"
task_type = "multiclass"
num_classes = 7
num_numerical_features = 16
num_categorical_features = 0
num_categorical = []
X_num_columns = [
    "Area",
    "Perimeter",
    "MajorAxisLength",
    "MinorAxisLength",
    "AspectRation",
    "Eccentricity",
    "ConvexArea",
    "EquivDiameter",
    "Extent",
    "Solidity",
    "roundness",
    "Compactness",
    "ShapeFactor1",
    "ShapeFactor2",
    "ShapeFactor3",
    "ShapeFactor4",
]
X_cat_columns = []
y_column = [
    "Class",
]

[train_params]
epochs = 20000
batch_size = 1000

[sample]
seed = 0
num_samples = 9527

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
