parent_dir = "exp/shopper/TabDDPM"
real_data_path = "Dataset/shopper/"
dataname = "shopper"
task_type = "binclass"
num_numerical_features = 10
num_categorical_features = 7
model_type = "mlp"
seed = 0
device = "cuda"
X_num_columns = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
]
X_cat_columns = [
    "Month",
    "OperatingSystems",
    "Browser",
    "Region",
    "TrafficType",
    "VisitorType",
    "Weekend",
]
y_column = [
    "Revenue",
]

[model_params]
num_classes = 2
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    256,
    1024,
    1024,
    1024,
    1024,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 50000
lr = 0.003
weight_decay = 0.0
batch_size = 2048

[Transform]
seed = 0
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"

[sample]
num_samples = 9247
batch_size = 9247
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.Transform]
seed = 0
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
