parent_dir = "exp/obesity/TabSyn"
real_data_path = "Dataset/obesity/"
task_type = "multiclass"
num_classes = 7
num_numerical_features = 8
num_categorical_features = 8
num_categorical = [
    2,
    2,
    2,
    4,
    2,
    2,
    4,
    5,
]
seed = 0
device = "cuda"
X_num_columns = [
    "Age",
    "Height",
    "Weight",
    "FCVC",
    "NCP",
    "CH2O",
    "FAF",
    "TUE",
]
X_cat_columns = [
    "Gender",
    "family_history_with_overweight",
    "FAVC",
    "CAEC",
    "SMOKE",
    "SCC",
    "CALC",
    "MTRANS",
]
y_column = [
    "NObeyesdad",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.001
wd = 0
d_token = 4
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024

[model_params]
is_y_cond = false
batch_size = 4096
num_epochs = 10001

[sample]
device = "cuda"
seed = 0

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
