parent_dir = "exp/shopper/TVAE"
real_data_path = "Dataset/shopper/"
dataname = "shopper"
seed = 0
device = "cuda"
task_type = "binclass"
num_classes = 2
num_numerical_features = 10
num_categorical_features = 7
num_categorical = [
    10,
    8,
    13,
    9,
    20,
    3,
    2,
]
X_num_columns = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
]
X_cat_columns = [
    "Month",
    "OperatingSystems",
    "Browser",
    "Region",
    "TrafficType",
    "VisitorType",
    "Weekend",
]
y_column = [
    "Revenue",
]

[train_params]
epochs = 30000
embedding_dim = 512
batch_size = 4096
loss_factor = 1.1675626917524105
compress_dims = [
    256,
    512,
]
decompress_dims = [
    256,
    512,
]

[sample]
seed = 0
num_samples = 8631

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
